---
ungrouped:
  hosts:
    ymlhost1:
    ymlhost2:

webservers:
  hosts:
    foo.example.com:
      ansible_user: NATH_USER
    bar.example.com:

dbservers:
  hosts:
    one.example.com:
        ansible_ssh_port: 2222
    two.example.com:
